name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 10,11,12,14,15,16,17 * * 1,2,3,4,5"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "lztxdyi@pm.me"
          git config --local user.name "Jimlier"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "The country becomes prosperous and the nation revitalizes the people's happiness"
          git push
