name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "lztxdyi@pm.me"
          git config --local user.name "Jimlier"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Want to fall in love this year"
          git push
